export function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }
  
  export const defaultBlackCards = [
    "I never expected _ at my birthday party.",
    "The secret ingredient in grandma's soup is _.",
    "Next on Netflix: a documentary about _.",
    "_ is the reason I got fired.",
    "In a world destroyed by _, only _ survives.",
    "My therapist says I need to stop thinking about _.",
    "The airline lost my luggage, but at least they found _.",
    "_: the #1 cause of awkward silence.",
    "What's the CEO's secret to success? _.",
    "I brought _ to show and tell. The teacher fainted.",
    "The museum's newest exhibit: _.",
    "Scientists recently discovered that _ can cure _.",
    "My dating profile says I'm really into _.",
    "The invention of _ changed everything.",
    "Breaking news: _ found in the White House.",
    "Step 1: _. Step 2: _. Step 3: Profit.",
    "The worst thing to say at a funeral: _.",
    "I got a tattoo of _ and immediately regretted it.",
    "_ is my love language.",
    "The school banned _ after the incident.",
    "If you can't handle _, you don't deserve _.",
    "My New Year's resolution is to stop _.",
    "_ + alcohol = bad decisions.",
    "The real reason the dinosaurs went extinct: _.",
    "I told my kids that _ builds character.",
  ];
  
  export const defaultWhiteCards = [
    "A questionable life choice",
    "An army of squirrels",
    "Passive-aggressive Post-it notes",
    "Accidentally replying all",
    "A midlife crisis motorcycle",
    "Pretending to work from home",
    "Googling symptoms at 3am",
    "An influencer's apology video",
    "Free samples at Costco",
    "That one friend who won't stop talking",
    "A strongly worded email",
    "Dancing alone in the kitchen",
    "Someone else's leftovers",
    "An uncomfortable amount of eye contact",
    "The WiFi going out",
    "Crying in the shower",
    "An awkward high five",
    "Motivational posters",
    "Retail therapy",
    "A conspiracy theory about birds",
    "Sleeping through the alarm",
    "A parking lot argument",
    "Too much hot sauce",
    "A haunted IKEA",
    "Ghosting someone",
    "The terms and conditions nobody reads",
    "An existential crisis",
    "Socks with sandals",
    "Being on mute for 10 minutes",
    "A very judgmental cat",
    "Cold pizza for breakfast",
    "Accidentally liking a 3-year-old photo",
    "Karaoke confidence",
    "A suspiciously cheap sushi restaurant",
    "Doom scrolling until 2am",
    "An out-of-office reply that's too honest",
    "The last slice of pizza",
    "Talking to plants",
    "An unhinged LinkedIn post",
    "Running out of coffee",
    "A surprise inspection",
    "Bubble wrap",
    "Main character energy",
    "A PowerPoint about feelings",
    "Forgetting someone's name immediately",
    "Impulse buying at Target",
    "A group project where you do all the work",
    "An unnecessarily loud sneeze",
    "Emotional support fries",
    "A passive-aggressive Yelp review",
  ];