export function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }
  
  export const defaultBlackCards = [
    "The secret to my productivity is _. 💼",
    "I told HR about _. 😬",
    "The office fridge was destroyed by _. 🧊",
    "My five-year plan involves _. 📅",
    "They found _ in the printer. 🖨️",
    "The new company mascot is _. 🏢",
    "My morning routine is incomplete without _. ☀️",
    "Nothing brings the team together like _. 🤝",
    "Our CEO just announced _ as the new company policy. 📋",
    "The real reason I work from home is _. 🏠",
    "My spirit animal is _. 🐾",
    "At my retirement party, they mentioned _. 🎉",
    "Scientists have discovered that _ is the key to happiness. 🔬",
    "According to my horoscope, I should avoid _ today. 🔮",
    "The team-building activity nobody asked for was _. 😅",
    "I can't focus in meetings without _. 🧠",
    "The highlight of my work week was _. ✨",
    "My resume lists _ as a special skill. 📄",
    "Life would be perfect if everyone just embraced _. 🌟",
    "The one thing keeping me from greatness is _. 💪",
    "I replaced my morning coffee with _. ☕",
    "My out-of-office message says I'm away due to _. 📧",
    "The new employee handbook dedicates an entire chapter to _. 📗",
    "My cat keeps knocking _ off the desk. 🐱",
    "I wrote an entire TED Talk about _. 🎤",
    "The real agenda of this meeting is _. 📋",
    "I asked for a raise because of my expertise in _. 💰",
    "Studies show that _ increases workplace morale by 47%. 📊",
    "The reason I was late to the meeting: _. ⏰",
    "My biggest professional achievement this year: _. 🥇",
    "The next big tech startup is going to disrupt _ forever. 🚀",
    "My therapist and I spend most of our time discussing _. 🛋️",
    "I put _ on my vision board and now I regret it. 🖼️",
    "The thing that finally broke the Zoom silence was _. 🎙️",
    "I thought adulting would be harder. Then I encountered _. 😅",
    "The weirdest thing in my search history is _. 🔍",
    "My autobiography will be titled: '_ and Other Mistakes.' 📚",
    "The only thing standing between me and success is _. 😤",
    "Nobody warned me that this job would require _. 😬",
    "The breakroom microwave smells like _ and broken dreams. 🍲",
    "I set an alarm for 5 AM to work on _. Then I turned it off. ⏰😴",
    "My New Year's resolution was _. I lasted three days. 🎆",
    "The secret meeting agenda item was _. 📋",
    "I listed _ on my LinkedIn as a core competency. 💼",
    "Our new team name is _. 🏢",
    "The reason the Wi-Fi went down: _. 📶😅",
    "The thing that actually motivated me this quarter: _. 💪",
    "I'm telling everyone my commute involves _ to earn their respect. 🚗",
    "The most passive-aggressive thing in our office is _. 📝",
    "I just discovered that my coworker's hidden talent is _. 🎭",
    "Nobody expected the meeting to end with _. 😳",
    "The onboarding process here includes a full day of _. 📋",
    "After reviewing your performance, we've decided to reward you with _. 🏆",
    "At the all-hands, the CEO accidentally revealed _. 😱",
    "What no one puts on the meeting agenda: _. 📋",
    "For Employee Appreciation Week, we're celebrating _. 🎉",
    "The real reason we can't print: _. 🖨️",
    "My phone wallpaper is _ and it keeps me going. 📱",
    "The next company retreat will be themed around _. 🌴",
    "I set three alarms: one for waking up, two for _. ⏰",
    "The strangest item on the company expense report: _. 💰",
    "My backup career plan involves _. 🔄",
    "The job description didn't mention _. 😬",
    "HR sent out a company-wide reminder about _. 📧",
    "Everyone on the call went quiet when I mentioned _. 🔇",
    "The reason I rearranged my entire living room: _. 🛋️",
    "Studies confirm that _ is the leading cause of Monday dread. 📊",
    "The theme of this year's company holiday party is _. 🎄",
    "I added _ to my calendar as a recurring event. Mistakes were made. 📅",
    "The real key performance indicator is _. 📈",
    "I stayed an extra hour at work because I forgot about _. ⏱️",
    "My most-used Slack reaction is _ and it says a lot about me. 💬",
    "The unofficial office rule about _ has gone unspoken for years. 🤫",
    "My performance review said I 'show great potential' at _. 📋",
    "The most heated debate in this office is about _. 🔥",
    "I know I've reached peak adulthood when I'm excited about _. 🏠",
    "The secret ingredient in every successful team meeting: _. 🤝",
    "I wrote a three-page email explaining _. Nobody read it. 📧",
    "What the quarterly report really says: _. 📊",
    "My biggest flex at the office potluck: _. 🍽️",
    "After the merger, the company values now include _. 🏢",
    "My biggest career regret is not learning more about _. 😔",
    "The thing I miss most about the office: _. 🏢",
    "Every project kickoff meeting ends with an action item for _. ✅",
    "The new hire was confused by our tradition of _. 😅",
    "My go-to response when I haven't read the thread: _. 📧",
    "Workplace wellness this month is focused on _. 🌱",
    "I set a goal to spend less time on _. That lasted 4 days. 📅",
    "The strangest thing I've Googled for work purposes: _. 🔍",
    "I've started carrying _ in my bag at all times. Just in case. 🎒",
    "Every office has that one person who is known for _. 🏢👀",
    "I accidentally CC'd the entire company on an email about _. 📧😬",
    "The thing that finally crashed the company server: _. 💻💥",
    "My therapy homework this week involves confronting _. 🛋️",
    "I meal-prepped an entire week of _ and ate takeout anyway. 🍱",
    "They made an entire slide deck just about _. 📊",
    "My cat judged me most harshly for _. 🐱",
    "The worst thing that can happen during a presentation: _. 📊",
    "I spent my entire lunch break thinking about _. 🥗💭",
    "The unofficial slogan of our team is _. 🏆",
    "A colleague walked in on me doing _. 😬",
    "My emergency desk snack drawer is full of _. 🍫",
    "I asked for a sick day because of _. 😷",
    "The last thing I said before my computer crashed: _. 💻😱",
    "My biggest personality trait, according to my coworkers, is _. 🏢",
    "I only come into the office for _. 🏢",
    "The strangest team norm we've developed is _. 🤔",
    "They said there would be snacks. The snacks were _. 🍩",
    "The meeting was supposed to be 30 minutes. It ran long because of _. ⏰",
    "I can't retire until I figure out _. 💼",
    "The last item on every meeting agenda: _. 📋",
    "My coworker's background music is _ and it's changing me. 🎵",
    "Nobody told me that working here would require knowing about _. 😶",
    "Our team Slack channel went silent for three days after someone posted _. 🔇",
    "The most creative excuse for missing a deadline: _. 😬⏰",
    "I've started describing _ as a 'learning opportunity.' 📚",
    "The thing I accidentally said out loud in a meeting: _. 😱",
    "My performance review noted that I have room to grow in _. 📋",
    "The best part of any company all-hands is _. 🏢",
    "I asked the new intern to help me with _ and we never spoke of it again. 😶",
    "My go-to icebreaker at every meeting: _. 🧊",
    "The last thing standing between me and the weekend: _. 🎉",
    "We hired a consultant to fix _. They made it worse. 💼",
    "The most misused word in our office is _. 🗣️",
    "I have a very strong opinion about _ that I will share unprompted. 💬",
    "My proudest moment this quarter was when I finally figured out _. 🏅",
    "Instead of fixing the actual problem, we decided to celebrate _. 🎊",
    "The strangest thing in our shared Google Drive folder: _. 📁",
    "I stayed for the free lunch and ended up learning about _. 🍕",
    "The most dramatic thing to happen in our office kitchen: _. 🍽️😱",
     "The AI told me that _ was the best approach. It was not. 🤖",
    "Our tech stack now includes _. Nobody asked why. ⚙️",
    "We gave the AI unsupervised access for one hour and it immediately started doing _. 🤖",
    "The production outage was caused by _. 🚨",
    "I asked the AI to improve our code and it suggested _. 🤖💡",
    "That Jira ticket has been in the backlog for 3 years because of _. 🎟️",
    "Our AI chatbot went viral for saying _ to a customer. 🤖📣",
    "The commit message just said _. 📝",
    "The most feared thing in our entire codebase is _. 💻😱",
    "The 'temporary' workaround is now in production and it is _. 🩹",
    "Nobody knows who owns _ but it's critical infrastructure. 💻",
    "We described _ as a feature instead of a bug. 🐛✨",
    "The AI assistant was trained on our Slack history and immediately started complaining about _. 🤖",
    "The sprint goal was _. We shipped nothing. 🏃",
    "The AI got confused and thought its job was _. 🤖🤔",
    "The intern's first PR broke _. They are now the lead engineer. 👩‍💻",
    "The postmortem officially blamed _. We all knew the real reason. 📋",
    "The CTO saw a demo of _ and immediately gave it 80% of the annual budget. 💼",
    "The AI started generating _ instead of code. Nobody stopped it for three weeks. 🤖",
    "Our entire CI/CD pipeline broke because of _. ⚙️💥",
    "The PR got 47 review comments, all of them about _. 🔀",
    "We use AI for everything except _. That's still a spreadsheet. 🤖📊",
    "The model hallucinated _ during a live customer demo. 🤖😱",
    "The AI passed the technical interview but completely failed when asked about _. 🤖",
    "We shipped _ to production on a Friday. The weekend was long. 🚀😩",
    "Our new AI policy explicitly prohibits using AI for _. The AI wrote the policy. 🤖📋",
    "The Slack bot started scheduling _ without being asked. 🤖📅",
    "The AI confidently explained _ with complete authority and zero accuracy. 🤖",
    "I tried to prompt engineer my way to _ and ended up with something much worse. 🤖",
    "The AWS bill was six figures. It was because of _. 💸",
    "Our machine learning model is highly accurate at predicting _. It cannot predict anything useful. 🤖",
    "The AI wrote our performance reviews and gave everyone full marks except for _. 🤖📋",
    "Deep in the legacy codebase, someone left a comment that just said _. 💻😱",
    "Tech leadership described _ as a 'strategic pivot.' 💼",
    "The developer who wrote _ left no documentation and is unreachable. 💻🌴",
    "We told the AI to 'be more human' and it started doing _. 🤖",
    "The model kept hallucinating _ so confidently that we almost shipped it. 🤖",
    "Every standup ends with someone assigning _ as a follow-up action item. 📋",
    "Our AI assistant now handles all _ for us. Badly. 🤖",
    "We ran out of budget because someone left _ running in the cloud overnight. ☁️💸",
    "The new AI hire has already automated _ and is eyeing the rest of us. 🤖👀",
    "The biggest threat to our product roadmap is _. 📋"
  ];
  
  export const defaultWhiteCards = [
    "A surprise nap 😴",
    "My emotional support snack 🍕",
    "Replying 'sounds good' to an email I didn't read 📧",
    "A dog in a tiny hat 🐶🎩",
    "Aggressively reorganizing my desk 🗂️",
    "The WiFi password 📶",
    "A passive-aggressive sticky note 📝",
    "Accidentally liking a 3-year-old photo 😬",
    "Unlimited vacation days 🏖️",
    "A coworker who microwaves fish 🐟",
    "The snooze button 😴",
    "Crying in a parking lot 🚗😭",
    "A motivational poster that doesn't motivate 🙃",
    "Free bagels in the break room 🥯",
    "A gif that perfectly captures my mood 📱",
    "A standing ovation from my cat 🐱👏",
    "Running on caffeine and anxiety ☕😰",
    "A strongly worded draft email I never sent ✉️",
    "The courage to finally unmute myself 🎤",
    "Saying 'I'll do it tomorrow' since 2019 📅",
    "A very long loading bar 💻⏳",
    "Existential dread at 9 AM 😶",
    "Putting my phone on Do Not Disturb 🔕",
    "A surprise birthday cake nobody wanted 🎂",
    "Being on mute the whole meeting 🔇",
    "A LinkedIn humble brag 💼",
    "An accidental reply-all 📨",
    "The last slice of office cake 🍰",
    "Finding $20 in an old jacket 💵",
    "Aggressively petting a stranger's dog 🐾",
    "A three-hour meeting that was literally an email 📧",
    "Extremely awkward elevator small talk 🛗",
    "The font Comic Sans 🖊️",
    "Pretending to be busy when the boss walks by 👀",
    "Gas station sushi 🍣",
    "Forgetting why I walked into the room 🚪🤔",
    "Autocorrect betrayal 😤",
    "A plant I somehow haven't killed yet 🌿",
    "A midday snack spiral 🍫",
    "Aggressively refreshing my inbox 📬",
    "The smell of a new notebook 📓✨",
    "A surprise compliment from a stranger 😊",
    "Overthinking a two-word text for 45 minutes 📱",
    "A deeply unnecessary Amazon purchase 📦",
    "Calling someone by the wrong name twice 😳",
    "Pure, unfiltered audacity 😤",
    "A task I've been avoiding for 6 months ⏳",
    "Winning at something no one else was competing in 🏆",
    "A full inbox at 8 AM on a Monday 😱",
    "Adding a task to my list just to cross it off ✅",
    "The vending machine eating my dollar 🤑",
    "A slideshow with 94 slides 📊",
    "A hug from a golden retriever 🐕❤️",
    "Realizing my camera was on the whole time 📷😬",
    "Texting back 'lol' instead of answering the question 😅",
    "An unsolicited life lesson from LinkedIn 💼✨",
    "Stress-cleaning at midnight 🧹🌙",
    "A deeply personal hot take about sandwiches 🥪",
    "Bringing snacks to a meeting to seem prepared 🍎",
    "A colleague who replies to every email with 'per my last email' 📧😬",
    "Making eye contact through a window and immediately looking away 👀",
    "The urge to reorganize everything instead of doing actual work 🗂️",
    "A backup plan for my backup plan 📋",
    "Sending a very serious email with a typo in the subject line 📧😬",
    "A fern named after my ex 🌿",
    "Lying awake thinking about something I said in 2013 😬🌙",
    "A surprisingly competitive game of office trivia 🏆",
    "Immediately forgetting someone's name after being introduced 😅",
    "The forbidden nap under the desk 🛋️💤",
    "A smoothie that tastes like regret 🥤😬",
    "Watching 6 hours of a show I don't even like 📺",
    "An unsolicited opinion about my lunch 🥗👀",
    "My entire personality during a power outage 🕯️",
    "A notification I immediately dismissed 🔔",
    "Speed-cleaning before a video call 🧹📹",
    "A nap disguised as 'deep thinking' 💭😴",
    "Forgetting to charge my phone at 3% 🔋😱",
    "Talking to my plants when no one's watching 🌱",
    "A grocery list in the notes app I'll never open 🛒",
    "The 'sent from my iPhone' excuse 📱",
    "Stress-eating an entire sleeve of crackers 🍘",
    "A perfectly timed thumbs up emoji 👍",
    "My 47 unread voicemails 📞",
    "Buying a planner I'll never use 📓",
    "The one pen that actually works 🖊️",
    "Telling someone 'I'll be there in 5' from my couch 🛋️",
    "A dog who understood the assignment 🐕✅",
    "Winning an argument in my head at 2 AM 🧠💬",
    "The confidence of someone who hasn't read the room 😎",
    "My inner monologue during a fire drill 🚨",
    "Holding the elevator for someone who is NOT rushing 🛗😑",
    "A surprisingly philosophical Uber driver 🚗💭",
    "Eating lunch at 10:45 AM 🥪",
    "The dramatic pause before announcing where we're ordering lunch 🍱",
    "A very competitive game of solitaire 🃏",
    "My face when someone cancels plans 😌🙌",
    "Answering a question with 'great question' to buy time ⏳",
    "Making a pros and cons list and ignoring it entirely 📝",
    "The group chat nobody texts back in 💬",
    "An oat milk latte with very strong opinions ☕",
    "The ringtone that hasn't been changed since 2009 📞",
    "Sending 'omw' from the shower 🚿",
    "Buying craft supplies for a hobby I'll abandon 🎨",
    "An alarm labeled 'DO NOT SNOOZE' that I snoozed 😴",
    "The glow of my phone at 1 AM 📱🌙",
    "A notification that changed everything 🔔",
    "Crying at a commercial for no reason 📺😢",
    "Attending a webinar I signed up for and immediately forgot about 💻",
    "The keyboard sound of someone typing loudly in a library 🖥️😤",
    "Pretending I'm on a call to avoid a conversation 📞",
    "The energy of a Tuesday afternoon 😐",
    "Unsubscribing from 1 email and getting 3 more 📧",
    "A scented candle that smells like ambition 🕯️",
    "My to-do list laughing at me 📋😂",
    "A surprise spider 🕷️😱",
    "The power of 'noted' in an email reply 📧",
    "A very enthusiastic onboarding video 📹✨",
    "Eating cereal for dinner without guilt 🥣",
    "My browser with 47 open tabs 💻",
    "The friend who texts 'K' 😑",
    "The one item in my cart for 3 months 🛒",
    "Forgetting my umbrella on the one rainy day 🌧️",
    "A perfectly timed sneeze during silence 🤧",
    "The smell of a thunderstorm through an open window 🌩️",
    "A fortune cookie that got too personal 🥠",
    "Trying to look busy while doing absolutely nothing 😐💻",
    "Overthinking a thumbs-up reaction on Slack 👍😬",
    "A spider plant named Gerald 🌿",
    "A birthday notification for someone I haven't spoken to in 8 years 🎂",
    "The coworker who always knows about the free food first 🍩👀",
    "My handwriting after age 25 ✍️",
    "Daydreaming about my lunch at 9 AM 🥗💭",
    "A mildly passive-aggressive 'per our conversation' 📧",
    "The 3 PM energy crash 😩⏰",
    "Pretending to understand a joke and laughing too late 😂😬",
    "A spreadsheet that somehow fixes itself 📊✨",
    "The sound of the office printer working for once 🖨️🎉",
    "Sending a calendar invite for a 30-second conversation 📅",
    "A documentary I watched instead of sleeping 📺🌙",
    "My reaction face during an all-hands meeting 😐",
    "A friend who calls instead of texting 😱📞",
    "The awkward handshake-hug hybrid 🤝🤗",
    "Writing 'per my last email' for the first time 😈",
    "My afternoon slump's emotional support candy bar 🍫",
    "An action item that will never be acted upon ✅",
    "My reaction when plans get cancelled last minute 😌🎉",
    "The one Slack emoji that means everything 🫠",
    "A grocery store encounter with my boss 😬🥦",
    "The pressure of being the first to say 'bye' on a call 👋",
    "The snack drawer at the bottom of my soul 🍫",
    "My signature 'almost ready' for 25 minutes 🕐",
    "A compliment from a coworker who usually ignores me 🌟",
    "The deep satisfaction of a perfectly organized cable 🔌",
    "Holding a pen in meetings to look like I'm taking notes 🖊️",
    "The one coworker who still prints everything 🖨️",
    "My personality during a software update ⏳😑",
    "A perfectly valid reason to stay home 🏠",
    "The ancient printer on its last ink cartridge 🖨️😵",
    "Vigorously nodding at something I don't understand 🤔😶",
    "The 'does anyone have any questions?' silence 🔇",
    "A professional headshot from 2014 📸",
    "The one meeting I somehow wasn't invited to 😤",
    "The person who types 'one sec' and vanishes for 20 minutes ⏳",
    "A parking spot that was closer than it looked 🚗✨",
    "My best idea at the worst possible time 💡🕚",
    "A quarterly report that raises more questions than it answers 📊",
    "Finishing a task 4 minutes before the deadline 🏃⏰",
    "Staying 5 extra minutes to prove I'm dedicated ⏱️😶",
    "The wrong Slack channel 😬💬",
    "Being personally victimized by a calendar reminder 📅😤",
    "A deeply personal relationship with my office chair 🪑",
    "The relief of walking out on a Friday 🚪🎉",
    "A notification that turned out to be a software update 😩📱",
    "The strategic bathroom break during a long call 🚽⏳",
    "Realizing everyone else on the call has a better background 🖥️😬",
    "The coffee machine on its last legs ☕😔",
    "Bringing big energy to a meeting nobody cares about ✨😤",
    "A highly specific complaint about the office thermostat 🌡️",
    "The task added to every sprint and never completed 🔄",
    "The satisfaction of closing 47 browser tabs at once 💻✅",
    "A very small but meaningful achievement 🏅",
    "The wrong impression I made on my first day 😬",
    "My password hint that makes no sense anymore 🔐🤔",
    "A recurring Zoom that haunts my Tuesday mornings 👻💻",
    "An unremarkable sandwich that somehow saved my day 🥪✨",
    "The one coworker who 'circles back' on everything 🔄",
    "The email I drafted and accidentally sent to myself 📧😳",
    "Zoning out so hard I missed the entire meeting 😶",
    "My reaction when I find out it's a half day 🎉",
    "An especially enthusiastic 'will do!' reply ✅",
    "My sense of urgency for everything but work 🏃",
    "The font size I use to make a document look longer 📝",
    "A meeting invitation with no agenda 😐📅",
    "The last person to join a Zoom call 😅",
    "The noise my chair makes at the worst possible time 🪑😬",
    "My confidence right before realizing I was wrong 😎😬",
    "The surprise twist in every all-hands meeting 😱",
    "An out-of-context screenshot 📸",
    "My unread Slack messages 💬😰",
    "The person who leaves dishes in the sink in the office kitchen 🍽️😤",
    "The 4:58 PM emergency email 📧😩",
    "Reorganizing my desktop instead of doing actual work 💻🗂️",
    "The background noise in every remote call 🔊😅",
    "The wrong answer I gave very confidently 😬✨",
    "My deep personal vendetta against Comic Sans 🖊️😤",
    "The urge to say 'this could have been an email' out loud 😤",
    "The coworker who responds to everything with a thumbs up 👍",
    "A strategic 'I'll have to check on that' 🤔",
    "A recurring nightmare about forgetting my password 🔐😱",
    "The one app I use for exactly one thing 📱",
    "Meal prepping on Sunday and ordering pizza by Tuesday 🍕",
    "The suspiciously cheerful email from IT 💻😐",
    "A to-do list item that just says 'stuff' 📝",
    "The brave soul who replies 'this seems off-topic' in a thread 📧",
    "The coworker who schedules 8 AM meetings voluntarily ⏰😤",
    "Sending a very sincere emoji to the wrong person 😳",
    "The smell of someone else's lunch at 10 AM 🍲",
    "A motivational speech I gave to my houseplants 🌿🎤",
    "Aggressively labeling my leftovers in the office fridge 🍱",
    "The printer running out of paper mid-job 🖨️😭",
    "A decision made entirely by flipping a coin 🪙",
    "Answering a question with 'it depends' and walking away 🚶",
    "The tab I've kept open for 6 weeks because 'I'll need it later' 💻",
    "A very relatable meme about deadlines 😅",
    "My 'work mode' playlist that somehow always shuffles to sad songs 🎵😭",
    "Waving back at someone who wasn't waving at me 😳👋",
    "The new office policy nobody asked for 📋",
    "Sending 'thanks!' twelve times in one email chain 📧",
    "The power of 'as discussed' in a passive-aggressive email 😈📧",
    "A coworker who narrates what they're doing all day 📢",
    "The lunch I forgot in the car 🚗😩🥗",
    "My face when someone says 'let's revisit this next quarter' 😐",
    "Waking up at 3 AM to send a work email 🌙📧",
    "The team that 'moves fast and breaks things' and then blames IT 💻😤",
    "A pull request with 47 comments and no approvals 🔀",
    "The AI that confidently gave the wrong answer 🤖❌",
    "Blaming it on a 'known issue' 🐛",
    "Copy-pasting from Stack Overflow without reading it 📋",
    "The README that hasn't been updated since 2018 📄",
    "An AI-generated email that sounds slightly off 🤖📧",
    "A dependency with 847 vulnerabilities 🔓",
    "Asking ChatGPT and using the very first answer 🤖✅",
    "The merge conflict nobody wants to resolve 🔀😤",
    "'It works on my machine' 💻🤷",
    "A chatbot that apologizes for everything 🤖😔",
    "Fixing a bug and creating three more 🐛🐛🐛",
    "The AI that went completely off-script 🤖😬",
    "A standup that becomes a philosophical debate 🧘",
    "Forgetting to push before going on vacation 🏖️😱",
    "A Jira ticket with no acceptance criteria 🎟️",
    "An LLM hallucination about a real API 🤖💭",
    "Accidentally deleting the production database 🗄️😱",
    "The 'temporary' fix from 2016 that's still in prod 🩹",
    "A Jira ticket titled 'misc' 🎟️",
    "Running AI on your data and getting back your deepest secrets 🤖🔮",
    "'Have you tried turning it off and on again?' 🔄",
    "A microservice that became a monolith 🏗️",
    "The AI that started scheduling its own meetings 📅🤖",
    "Tech debt described as 'character' 💸",
    "A 3-hour onboarding session about password policy 🔐",
    "The engineer who says everything is 'trivial' ⚙️",
    "Shipping code at 4:59 PM on a Friday 🚀😅",
    "The AI model trained on our Slack messages 🤖💬",
    "A YAML file that's broken for reasons no one can explain 📄",
    "The sprint velocity that was purely 'aspirational' 📈",
    "An AI that only generates corporate buzzwords 🤖📊",
    "An error message that just says 'something went wrong' ❌",
    "The Kubernetes cluster nobody fully understands ⚓",
    "Prompt engineering as a full-time career 🤖✍️",
    "A recursive bug that somehow fixed itself 🔄🐛",
    "Disabling the linter to ship faster ⚡",
    "Dark mode that destroys your productivity by looking too good 🌑💻",
    "An API that deprecated itself 🔌",
    "The AI feature that turned out to be an if-statement 🤖➡️",
    "Stack Overflow going down on a critical deadline day 😱",
    "A ten-minute build pipeline that builds nothing 🏗️⏱️",
    "Using AI to write the tests for the AI-written code 🤖✅",
    "A boolean named 'flag2' 🚩",
    "A password reset that resets every 14 days 🔐😩",
    "The AWS bill nobody budgeted for 💸",
    "A 500-line function with no comments 📜",
    "The AI that replaced the intern but not the manager 🤖",
    "Hotfixing a hotfix 🩹🩹",
    "The chatbot that went rogue during the demo 🤖😱",
    "Commenting out code instead of deleting it 💻",
    "AI-generated art of the company mascot looking vaguely menacing 🤖🎨",
    "A sprint retro where everyone blames the tools 🛠️",
    "The AI ethics team being overruled by the deadline 🤖⏰",
    "Deploying with 'YOLO' in the commit message 🚀",
    "A chatbot that gives unsolicited legal advice 🤖⚖️",
    "npm install taking longer than the feature itself 📦⏳",
    "The AI that learned to say 'as per my last prompt' 🤖📧",
    "An API with 14 versions still simultaneously in production 🔌",
    "The coworker who makes everything a blockchain solution ⛓️",
    "A regex that breaks three months later and no one knows why 🔍😤",
    "Using AI for everything except the problem you actually have 🤖",
    "The Slack bot that got way too comfortable 🤖💬",
    "A unit test that only checks that the function exists 🧪",
    "Twelve microservices to send one email 📧⚙️",
    "A standup where nobody has any blockers but nothing is done ✅😶",
    "The developer who hasn't left the codebase in 7 years and knows everything 🧙",
    "A loading spinner with no end in sight 🔄💻",
    "Refactoring instead of fixing the actual bug 🛠️",
    "The AI that learned our meeting patterns and called in sick 🤖🤒",
    "A variable named 'x2' 📝",
    "An LLM that writes better commit messages than our entire team 🤖📝",
    "Asking an AI to summarize the AI-generated document 🤖📄",
    "The hottest new framework that will be abandoned in 18 months 🔥",
    "'Move fast and break things' but the thing that broke was production 🚀💥",
    "An AI model confidently citing a paper that doesn't exist 🤖📚",
    "The algorithm that works perfectly in testing and nowhere else 🧪",
    "Closing tickets as 'cannot reproduce' 🎟️🚫"
  ];